version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: buffet_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=buffet_database
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app_buffet
    ports:
       - 3333:3333
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local